client_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('clients.urls')),
]

clients/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'clients'

urlpatterns = [
    path('', views.client_list, name='client_list'),
    path('new/', views.client_new, name='client_create'),
    path('<int:pk>/', views.client_detail, name='client_detail'),
    path('<int:pk>/edit/', views.client_edit, name='client_edit'),
    path('<int:pk>/delete/', views.client_delete, name='client_delete'),
    path('search/', views.client_search, name='client_search'),
    path('client/<int:pk>/photo/', views.client_photo, name='client_photo')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

clients/models.py
from django.db import models

class Client(models.Model):
    first_name = models.CharField(max_length=20, verbose_name='Имя')
    last_name = models.CharField(max_length=20, verbose_name='Фамилия')
    middle_name = models.CharField(max_length=20, verbose_name='Отчество')
    date_of_birth = models.DateField(verbose_name='Дата рождения')
    phone_number = models.CharField(max_length=20, verbose_name='Номер телефона')
    email = models.EmailField()
    address = models.TextField(max_length=100, verbose_name='Адрес места жительства')
    education = models.TextField(max_length=100, verbose_name='Образование',blank=True, null=True)
    workplace = models.TextField(blank=True, null=True, max_length=100, verbose_name='Место работы')
    position = models.TextField(blank=True, null=True, max_length=100, verbose_name='Должность')
    children = models.TextField(blank=True, null=True, max_length=100, verbose_name='Семейное положение, дети')
    life_events = models.TextField(blank=True, null=True,max_length=100, verbose_name='Жизненные события клиента')
    illnesses = models.TextField(blank=True, null=True, verbose_name='Заболевания, жалобы клиента')
    diagnosis = models.TextField(blank=True, null=True, max_length=100, verbose_name='Диагноз')
    last_consultation_date = models.DateField(blank=True, null=True, verbose_name='Дата последней консультации')
    photo = models.ImageField(upload_to='clients/photos', blank=True, null=True)


    def __str__(self):
        return f"{self.last_name} {self.first_name} {self.middle_name}"

clients/forms.py
from django.forms.widgets import DateInput
from django import forms
from .models import Client

class ClientForm(forms.ModelForm):
    class Meta:
        model = Client
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['photo'].widget.attrs['class'] = 'form-control-file'

    def save(self, commit=True):
        instance = super().save(commit=False)
        if self.cleaned_data['photo']:
            instance.photo = self.cleaned_data['photo']
        if commit:
            instance.save()
        return instance
class SearchForm(forms.Form):
    query = forms.CharField(label='Поиск', max_length=40)

class CustomDateInput(DateInput):
    input_type = 'date'
    format = '%d.%m.%Y'

clients/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Client
from .forms import ClientForm, SearchForm
from django.db.models import Q
from django.http import HttpResponseNotFound, HttpResponse


def client_list(request):
    clients = Client.objects.all()
    return render(request, 'clients/client_list.html', {'clients': clients})

def client_detail(request, pk):
    client = get_object_or_404(Client, pk=pk)
    return render(request, 'clients/client_detail.html', {'client': client})

def client_new(request):
    if request.method == "POST":
        form = ClientForm(request.POST, request.FILES)
        if form.is_valid():
            client = form.save(commit=False)
            client.save()
            return redirect('clients:client_list')
    else:
        form = ClientForm()
    return render(request, 'clients/client_edit.html', {'form': form})


def client_edit(request, pk):
    client = get_object_or_404(Client, pk=pk)
    if request.method == 'POST':
        form = ClientForm(request.POST, request.FILES, instance=client)
        if form.is_valid():
            form.save()
            return redirect('clients:client_list')
        elif 'cancel' in request.POST:
            return redirect('clients:client_list')
    else:
        form = ClientForm(instance=client)
    return render(request, 'clients/client_edit.html', {'form': form, 'client': client})

def client_delete(request, pk):
    client = get_object_or_404(Client, pk=pk)

    if request.method == "POST":
        if 'confirm' in request.POST:
            client.delete()
            return redirect('clients:client_list')
        elif 'cancel' in request.POST:
            return redirect('clients:client_list')

    return render(request, 'clients/client_delete.html', {'client': client})


def client_search(request):
    if request.method == "POST":
        form = SearchForm(request.POST)
        if form.is_valid():
            query = form.cleaned_data['query']
            clients = Client.objects.filter(
                Q(first_name__icontains=query) |
                Q(last_name__icontains=query) |
                Q(middle_name__icontains=query) |
                Q(date_of_birth__icontains=query) |
                Q(phone_number__icontains=query) |
                Q(address__icontains=query) |
                Q(email__icontains=query)
            )
            return render(request, 'clients/search_results.html', {'clients': clients})
    else:
        form = SearchForm()
    return render(request, 'clients/client_search.html', {'form': form})

def client_photo(request, pk):
    client = get_object_or_404(Client, pk=pk)
    if not client.photo:
        return HttpResponseNotFound()
    return HttpResponse(client.photo, content_type='image/jpeg')

clients/templates/clients/base.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>{% block title %}{% endblock %}</title>
  {% load static %}
  <link rel="stylesheet" href="{% static 'clients/css/style.css' %}">
</head>
  <body>
  <nav>
    <ul>
      <li><h3><button onclick="location.href='{% url 'clients:client_list' %}'">Клиенты</button></h3></li>
      <li><h3><button onclick="location.href='{% url 'clients:client_create' %}'">Добавить клиента</button></h3></li>
      <li><h3><button onclick="location.href='{% url 'clients:client_search' %}'">Поиск клиента</button></h3></li>
    </ul>
  </nav>
  <main>
    {% block content %}{% endblock %}
  </main>
  </body>
</html>

clients/templates/clients/client_delete.html
{% extends 'clients/base.html' %}
{% block content %}
  <h2 style="text-align:center">Удаление клиента</h2>
<div id="client-delete-container">
  <h4>Вы действительно хотите удалить клиента {{ client.first_name }} {{ client.last_name }}?</h4>

  <form method="post">
    {% csrf_token %}
    <br>
    <button type="submit" name="confirm">Delete</button>
    <br>
    <button type="submit" name="cancel">Cancel</button>
  </form>
<script>
  $(document).ready(function() {
    // Show the modal when the delete button is clicked
    $('.btn-danger').click(function() {
      $('#confirmDeleteModal').modal('show');
    });
  });
</script>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
</div>
{% endblock %}

clients/templates/clients/client_detail.html
{% extends 'clients/base.html' %}

{% block content %}
{% load static %}
  <h1 style="text-align:center">Подробная информация о клиенте</h1>
<div id="client-detail-container">
  <ul>
    {% if client.photo %}
    <img class="client-photo" src="{{ client.photo.url }}" alt="Photo">
    {% else %}
    <img class="client-photo" src="{% static 'clients/css/no-photo.jpg' %}" alt="Фото заглушка">
    {% endif %}
    <br>

    <pre>
    <li><strong>Имя:</strong> {{ client.first_name }}</li>
    <li><strong>Отчество:</strong> {{ client.middle_name }}</li>
    <li><strong>Фамилия:</strong> {{ client.last_name }}</li>
    <li><strong>Дата рождения:</strong> {{ client.date_of_birth }}</li>
    <li><strong>Номер телефона:</strong> {{ client.phone_number }}</li>
    <li><strong>Email:</strong> {{ client.email }}</li>
    <li><strong>Адрес места жительства:</strong> {{ client.address }}</li>
    <li><strong>Образование:</strong> {{ client.education }}</li>
    <li><strong>Место работы:</strong> {{ client.workplace }}</li>
    <li><strong>Должность:</strong> {{ client.position }}</li>
    <li><strong>Семейное положение, дети:</strong> {{ client.children }}</li>
    <li><strong>Жизненные события клиента:</strong> {{ client.life_events }}</li>
    <li><strong>Заболевания, жалобы клиента:</strong> {{ client.illnesses }}</li>
    <li><strong>Диагноз:</strong> {{ client.diagnosis }}</li>
    <li><strong>Дата последней консультации:</strong> {{ client.last_consultation_date }}</li>
    </pre>
  </ul>
  <button style="margin-left:250px; margin-top:20px" onclick="location.href='{% url 'clients:client_edit' pk=client.pk %}'">Изменить</button>
  <br>
  <br>
  <button style="margin-left:260px"  type="button" onclick="window.history.back()">Назад</button>
</div>


{% endblock %}

clients/templates/clients/client_edit.html
{% extends 'clients/base.html' %}

{% block content %}
  <h1 style="text-align:center">Добавить / Редактировать клиента</h1>
<div id="client-edit-container" class="input">
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}

    <br>
    <button type="submit" class="btn btn-primary">Сохранить</button>
    <br>
    <button type="button" onclick="window.history.back()">Назад</button>
  </form>

</div>
{% endblock %}

clients/templates/clients/client_list.html
{% extends 'clients/base.html' %}
{% load static %}
{% block content %}

<h1 style="text-align:center">Клиенты</h1>
<div id="client-list-container">
<table>
    <tr>
        <th>№ п/п</th>
        <th>Фамилия Имя Отчество</th>
        <th>Дата рождения</th>
        <th>Телефон</th>
        <th>Адрес</th>
        <th>Действия</th>
    </tr>
    {% for client in clients %}
    <tr>
        <td>{{ forloop.counter }}</td>
        <td>{{ client }}</td>
        <td>{{ client.date_of_birth }}</td>
        <td>{{ client.phone_number }}</td>
        <td>{{ client.address }}</td>
        <td>
            <button onclick="location.href='{% url 'clients:client_detail' pk=client.pk %}'">Подробнее</button> |
            <button onclick="location.href='{% url 'clients:client_edit' pk=client.pk %}'">Изменить</button> |
            <button onclick="location.href='{% url 'clients:client_delete' pk=client.pk %}'">Удалить</button>

        </td>
    </tr>
    {% empty %}
    <tr>
        <td colspan="6">Нет клиентов</td>
    </tr>
    {% endfor %}
</table>
</div>
{% endblock %}

clients/templates/clients/client_search.html
{% extends 'clients/base.html' %}

{% block content %}

  <h1 style="text-align:center">Поиск клиента</h1>
<div id="client-search-container">
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Найти</button>

  </form>
  {% if clients %}
    <h2>Результат поиска</h2>
    <ul>
    {% for client in clients %}
      <li><a href="{% url 'clients:client_detail' pk=client.pk %}">{{ client }}</a></li>
    {% endfor %}
    </ul>
  {% endif %}
</div>
{% endblock %}

clients/templates/clients/search_results.html
{% extends 'clients/base.html' %}

{% block content %}
  <h1 style="text-align:center">Результаты поиска</h1>
<div id="client-results-container">
  {% if clients %}
    <ul>
      {% for client in clients %}
        <li>
          <a href="{% url 'clients:client_detail' client.pk %}">{{ client }}</a>
        </li>
      {% endfor %}
    </ul>
  {% else %}
  <br>
    <h4 style="margin-left: 20px;"> По Вашему запросу ничего не найдено !</h4>
  <br>
  <br>
  {% endif %}
<button id="my-button"  type="button" onclick="window.history.back()">Назад к поиску</button>
</div>
  {% endblock %}